"""Create aquariums table

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2023-11-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquariums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('volume_liters', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aquarium'
    )
    op.create_index(op.f('ix_aquariums_id'), 'aquariums', ['id'], unique=False, schema='aquarium')
    op.create_index(op.f('ix_aquariums_name'), 'aquariums', ['name'], unique=False, schema='aquarium')
    op.create_index(op.f('ix_aquariums_user_id'), 'aquariums', ['user_id'], unique=False, schema='aquarium')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aquariums_user_id'), table_name='aquariums', schema='aquarium')
    op.drop_index(op.f('ix_aquariums_name'), table_name='aquariums', schema='aquarium')
    op.drop_index(op.f('ix_aquariums_id'), table_name='aquariums', schema='aquarium')
    op.drop_table('aquariums', schema='aquarium')
    # ### end Alembic commands ###
